### DISCUSSION TITLE
Finally got the forecast :D ...

### DISCUSSION THREAD

**Discussion by Paul1865** [fsaris/home-assistant-zonneplan-one#47] [Show and tell]
Maybe there is a better way, but I did this with the apexcharts card: [https://github.com/RomRider/apexcharts-card](url)
Colors are a little off, so feel free to change :) .
Instead of fixed values for the colors, it it better to check forcast.tariff_group (low | normal | high), but I don't know how to do it :p .

![image](https://user-images.githubusercontent.com/17167055/218252894-7d0c8614-4ab3-4ab9-8037-5ef376185144.png)

### ATTRIBUTES
```yaml
state_class: measurement
forecast: 
- electricity_price: 3433617
  tariff_group: low
  solar_percentage: 0
  solar_yield: 0
  datetime: '2023-01-20T20:00:00.000000Z'
  sustainability_score: 129
  carbon_footprint_in_grams: 3005
```

### CODE
```yaml
type: custom:apexcharts-card
apex_config:
  legend:
    show: false
    min: 0
  grid:
    lines:
      show: true
    borderColor: '#333'
    strokeDashArray: 0
  xaxis:
    axisBorder:
      show: true
      color: '#333'
      offsetX: 0
      offsetY: 0
experimental:
  color_threshold: true
header:
  title: Zonneplan Forecast tariffs
  show: true
  show_states: true
  colorize_states: true
span:
  start: hour
yaxis:
  - id: both
    min: '|-0.01|'
    max: '|+0.01|'
    decimals: 2
series:
  - entity: sensor.zonneplan_current_electricity_tariff
    float_precision: 3
    show:
      in_chart: false
      name_in_header: true
  - entity: sensor.zonneplan_current_electricity_tariff
    type: column
    group_by:
      func: raw
    float_precision: 3
    color_threshold:
      - value: 0
        color: rgb(137,104,205);
      - value: 0.2
        color: rgb(102,153,204);
      - value: 0.25
        color: rgb(0,139,69);
      - value: 0.32
        color: rgb(189,183,107);
      - value: 0.37
        color: rgb(238, 118, 0);
    show:
      in_header: false
      name_in_header: false
      datalabels: false
    data_generator: |
      return entity.attributes.forecast.map((entry) => {
            return [new Date(entry.datetime), entry.electricity_price/10000000];
          });

```

**Comment by rinseringma** [comment]
Nice! Very cool! Just implemented it, works great!

**Reply by Paul1865** [reply]
Changed y-axis to

```yaml
yaxis:
  - id: both
    min: '|-0.01|'
    max: '|+0.01|'
    decimals: 2
```
