### ISSUE TITLE
Double sensors?

### ISSUE THREAD

**Issue by renslinden** [fsaris/home-assistant-zonneplan-one#25]
Just wondering why I do have multiple sensors with the same data. An error or is it designed as intended?

Can someone elaborate? Thanks.

```yaml
  - entity: sensor.zonneplan_current_electricity_tariff
  - entity: sensor.zonneplan_current_electricity_tariff_2
  - entity: sensor.zonneplan_current_electricity_tariff_3
  - entity: sensor.zonneplan_current_gas_tariff
  - entity: sensor.zonneplan_current_gas_tariff_2
  - entity: sensor.zonneplan_current_gas_tariff_3
```
