### ISSUE TITLE
Zonneplan prices (current and forecast) are of yesterday instead of today

### ISSUE THREAD

**Issue by loedeman** [fsaris/home-assistant-zonneplan-one#27]
Recently, Zonneplan started providing the past day in the Home Screen chart. It seems the integration uses those prices now as current and forecast prices. This makes using the integration impossible 🤔😉… Could you please have a look into this?

**Comment by loedeman** [comment]
![3C27C6B7-2109-481B-8353-E5BD8A5E98D7](https://user-images.githubusercontent.com/355132/202388608-354c68d2-f6b3-4e8c-b9f3-43adab90a25f.png)
![872AEB0C-5853-421F-8E04-A97BA41762B9](https://user-images.githubusercontent.com/355132/202388625-9e79842d-1ce7-498c-954a-339a701650cb.png)
![CC6FD6C5-BB2B-4269-A8E4-161A41A966BE](https://user-images.githubusercontent.com/355132/202388636-281cceff-76f6-4c12-bcf4-9b6a9fdbf8b7.png)

**Comment by loedeman** [comment]
Dit is de JSON van de uurprijzen API call. Er staan 57 items in de lijst :-) ...
[Zonneplan hourly rates.txt](https://github.com/fsaris/home-assistant-zonneplan-one/files/10032563/Zonneplan.hourly.rates.txt)

**Comment by loedeman** [comment]
I created a PR for this issue ;-). https://github.com/fsaris/home-assistant-zonneplan-one/pull/28

**Comment by fsaris** [comment]
Tnx for the pr

Can you also verify this gives the expected values  in the morning (before 13.00)? See also https://github.com/fsaris/home-assistant-zonneplan-one/issues/22#issuecomment-1296244910

**Comment by loedeman** [comment]
I will look into that when I wake up tomorrow 😉! Will keep you posted!

**Comment by loedeman** [comment]
Just checked, the fix also works for the morning (before 1PM). Have a look at the current price data...
[Zonneplan hourly rates (before 1PM).txt](https://github.com/fsaris/home-assistant-zonneplan-one/files/10039507/Zonneplan.hourly.rates.before.1PM.txt)

**Comment by nl0pvm** [comment]
I know this is open source but.... it would be nice if this is released ASAP. As currently all zonneplan API dependent integrations are broken and switching based on yesterday's price data :P

**Comment by loedeman** [comment]
> I know this is open source but.... it would be nice if this is released ASAP. As currently all zonneplan API dependent integrations are broken and switching based on yesterday's price data :P

I could not agree more - patience is a real virtue though 😀. It should just be a push of the button, isn’t it?

**Comment by fsaris** [comment]
It's released 😉

Tnx @loedeman for the fix

**Comment by lenwar** [comment]
Apologies to hijack this topic but:

@loedeman how did you manage those graphs? I’ve been poking around for weeks to get something like that. Would you mind sharing your yaml?

**Comment by loedeman** [comment]
> Apologies to hijack this topic but:
> 
> @loedeman how did you manage those graphs? I’ve been poking around for weeks to get something like that. Would you mind sharing your yaml?

Hi @lenwar sure, here are the YAMLs for the Lovelace components:

```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
apex_config:
  legend:
    show: false
header:
  show: true
  title: Elektriciteitsprijs komende 8 uur
  standard_format: true
graph_span: 8h
span:
  offset: +8h
yaxis:
  - decimals: 2
series:
  - entity: sensor.zonneplan_forcast_tariff_hour_8
    name: Forecast
    curve: stepline
    float_precision: 2
    offset: '-8h'
    show:
      offset_in_name: false
    color_threshold:
      - value: -1
        color: green
      - value: 0.2
        color: green
      - value: 0.3
        color: orange
      - value: 0.4
        color: red
```
... and ...
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
apex_config:
  legend:
    show: false
header:
  show: true
  show_states: true
graph_span: 168h
yaxis:
  - id: elec
    decimals: 2
  - id: gas
    opposite: true
    decimals: 2
series:
  - entity: sensor.zonneplan_current_electricity_tariff
    name: Elektriciteitsprijs
    yaxis_id: elec
    curve: stepline
    stroke_width: 2
    float_precision: 2
    color_threshold:
      - value: -1
        color: green
      - value: 0.2
        color: green
      - value: 0.3
        color: orange
      - value: 0.4
        color: red
    show:
      header_color_threshold: true
  - entity: sensor.zonneplan_current_gas_tariff
    name: Gasprijs
    yaxis_id: gas
    curve: stepline
    opacity: 0.7
    stroke_width: 3
    float_precision: 2
    fill_raw: last
    color_threshold:
      - value: 0
        color: green
      - value: 0.75
        color: green
      - value: 1
        color: blue
      - value: 1.5
        color: gray
    show:
      header_color_threshold: true
```
